### ISSUE TITLE
C_GetAttributeValue does not set the attribute length in all cases

### ISSUE THREAD

**Issue by sbertin-telular** [FreeRTOS/corePKCS11#170]
The attribute length is only set when the pointer is NULL. It should also be set in cases where the buffer is too large or too small.

From [PKCS11-base-v2.40](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.doc):
For each (type, pValue, ulValueLen) triple in the template, C_GetAttributeValue performs the following algorithm:
1.	If the specified attribute (i.e., the attribute specified by the type field) for the object cannot be revealed because the object is sensitive or unextractable, then the ulValueLen field in that triple is modified to hold the value CK_UNAVAILABLE_INFORMATION.
2.	Otherwise, if the specified value for the object is invalid (the object does not possess such an attribute), then the ulValueLen field in that triple is modified to hold the value CK_UNAVAILABLE_INFORMATION.
3.	Otherwise, if the pValue field has the value NULL_PTR, then the ulValueLen field is modified to hold the exact length of the specified attribute for the object.
4.	Otherwise, if the length specified in ulValueLen is large enough to hold the value of the specified attribute for the object, then that attribute is copied into the buffer located at pValue, and the ulValueLen field is modified to hold the exact length of the attribute.
5.	Otherwise, the ulValueLen field is modified to hold the value CK_UNAVAILABLE_INFORMATION.

**Comment by paulbartell** [comment]
@sbertin-telular Thanks for the report. I will take a look.

**Comment by chinglee-iot** [comment]
@sbertin-telular 
I have created a pull request to address this issue, and I would like to invite you to review the proposed changes to see if they adequately resolve the issue.
