### ISSUE TITLE
compilation error when logLevel set to DEBUG

### ISSUE THREAD

**Issue by YTvW** [FreeRTOS/corePKCS11#185]
When compiling for ESP32 using the esp-aws-iot library the build fails due to an error in the corePKCS11 library

On line 452 in the file source/portable/mbedtls/core_pkcs11_mbedtls.c
the log debug call fails to compile with the following error:
`error: format '%ld' expects argument of type 'long int', but argument 6 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]`

Line:
`  LogDebug( ( "Ready to sign: xSignatureLength=%ld *pulSignatureLen=%ld", xSignatureLength,*pulSignatureLen ) );`

Proposed change:
`LogDebug( ( "Ready to sign: xSignatureLength=%ld *pulSignatureLen=%ld", ( long int )xSignatureLength,( long int ) *pulSignatureLen ) );`

**Comment by xuelix** [comment]
Thanks for reporting the issue.  Would it be more fitting to set the format to %lu instead?   
We'll take a look and have it fixed.

**Comment by paulbartell** [comment]
@YTvW I'm having trouble reproducing the compilation error. 

Can you confirm the following so I can reproduce the compilation error:
1. Which version of esp-idf
2. What target you are building for (esp32, esp32c3 etc)
3. Which version of gcc you are using

Thanks much.
